# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "FAQ Anywhere"
client_id = "6e9774a8a022e1d10fa6681bec123b0a"
application_url = "https://frank-verified-peacock.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://frank-verified-peacock.ngrok-free.app/authenticate" ]

[webhooks]
api_version = "2023-10"

[app_proxy]
url = "https://frank-verified-peacock.ngrok-free.app/proxy"
subpath = "faq-anywhere-proxy"
prefix = "apps"

[pos]
embedded = false

[build]
dev_store_url = "orayon-testing-store.myshopify.com"
